### ISSUE TITLE
Make error with TP-Link TL-WN722N 

### ISSUE THREAD

**Issue by stingyman12** [kimocoder/realtek_rtwifi#15]
while using make command and sudo make install command 
i get this error

─(root💀kali)-[/home/kali/realtek_rtwifi]
└─# make
make -C /lib/modules/5.10.0-kali3-amd64/build M=/home/kali/realtek_rtwifi modules
make[1]: *** /lib/modules/5.10.0-kali3-amd64/build: No such file or directory.  Stop.
make: *** [Makefile:14: modules] Error 2
                                                                             
┌──(root💀kali)-[/home/kali/realtek_rtwifi]
└─# sudo make install                                                    2 ⨯
make -C /lib/modules/5.10.0-kali3-amd64/build M=/home/kali/realtek_rtwifi modules
make[1]: *** /lib/modules/5.10.0-kali3-amd64/build: No such file or directory.  Stop.
make: *** [Makefile:14: modules] Error 2

My kali-Linux version

Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        2021.1
Codename:       kali-rolling

Using iwconfig (my wireless device is connected to kali through VMware)

─$ iwconfig
lo        no wireless extensions.

eth0      no wireless extensions.

I get this 
Thank you and waiting for a solution

**Comment by SmillerMP** [comment]
@stingyman12 
Do you have de linux headers installed?

**Comment by SmillerMP** [comment]
@stingyman12 
Do you have de linux headers installed?

**Comment by VitalyBykhalov** [comment]
> i get this error
It seems it can be solved like this:
uname -r
You will see your kernel version. And you need to find the corresponding headers using the command:
apt-cache search linux-headers
Install them and rerun the make.

**Comment by stingyman12** [comment]
> @stingyman12
> Do you have de linux headers installed?
> 
> Try
> 
> ```
> ​sudo apt-get install linux-headers-$(uname -r)
> ```

Thanks that worked
