### ISSUE TITLE
Problem with make menuconfig !!!

### ISSUE THREAD

**Issue by BeingDatta** [kimocoder/realtek_rtwifi#2]
i downloaded realtek-wifi via gitclone renamed as realtek paste the folder under **/kernel-folder/drivers/net/wireless/renamed-realtek-folder** because by default i dont have any realtek folder in there instead i have **rtlwifi** folder in that location.

Then I did the following change is Makefile and Kconfig under **/kernel-folder/drivers/net/wireless/renamed-realtek-folder** including quotes

Makefile = "obj-$(CONFIG_RTL8XXXU) += rtl8xxxu/"
Kconfig = source "drivers/net/wireless/realtek/rtl8xxxu/Kconfig"

I pasted them as it is i have written but unable to find them under menuconfig device-drivers Network-Devices-Support Wireless.

where should i find them and am i doing everything alright ???

Regards.

**Comment by Si-i3ima** [comment]
CONFIG_RTL8XXXU
if i not wrong

**Comment by BeingDatta** [comment]
> CONFIG_RTL8XXXU
> if i not wrong

i didnt get u there what do u mean by that CONFIG_RTL8XXXU=y in xyz_defconfig ?

**Comment by BeingDatta** [comment]
got it opened another issue
