### ISSUE TITLE
make problem 

### ISSUE THREAD

**Issue by SmillerMP** [kimocoder/realtek_rtwifi#5]
i try to install but...
![Captura de pantalla de 2020-12-28 14-44-29](https://user-images.githubusercontent.com/57497888/103242289-58576800-491b-11eb-9921-89338201b80f.png)

@kimocoder can you help me?

**Comment by kimocoder** [comment]
@SmillerMP Sure;

`git pull && make clean && make -j4 && make install`

**Comment by SmillerMP** [comment]
@kimocoder thank you, but now i have other problem 

I already put the drivers on the blacklist
![Captura de pantalla de 2020-12-28 16-40-02](https://user-images.githubusercontent.com/57497888/103247219-c4da6300-492b-11eb-8e74-60a617117b0b.png)

and make and install 
![Captura de pantalla de 2020-12-28 16-41-26](https://user-images.githubusercontent.com/57497888/103247230-cdcb3480-492b-11eb-9fc8-300452d365f9.png)

but now the system does not recognize my adapter

![Captura de pantalla de 2020-12-28 16-42-15](https://user-images.githubusercontent.com/57497888/103247255-e3d8f500-492b-11eb-81bc-c7e308235352.png)

help plis :)

**Comment by kimocoder** [comment]
Need some outputs;

`uname -a
lsusb
dmesg | tail
`

**Comment by SmillerMP** [comment]
![Captura de pantalla de 2020-12-28 16-54-38](https://user-images.githubusercontent.com/57497888/103247694-67471600-492d-11eb-9867-9a306543c6d6.png)

**Comment by kimocoder** [comment]
And that is a RTL8723DE chipsets.. not supported by this repo, but rtw88 driver (the new one around) is a great driver by noe and for the future. rtw88 should support that chipset

**Comment by SmillerMP** [comment]
@kimocoder amm
i have the tl-wn722n v3 with the rtl8188eus 
the RTL8723DE its other

**Comment by kimocoder** [comment]
output from "rfkill list"

And plug the adapter, then run "dmeg | tail" straight after

**Comment by SmillerMP** [comment]
okay i run the comand before and after to conect de adapter 

![Captura de pantalla de 2020-12-28 17-14-33](https://user-images.githubusercontent.com/57497888/103248425-2bfa1680-4930-11eb-84ba-39d323ff6349.png)

**Comment by kimocoder** [comment]
> @SmillerMP Sure;
> 
> `git pull && make clean && make -j4 && make install`

Do this again. I've added the VID/PID.

**Comment by SmillerMP** [comment]
ready!! 

![Captura de pantalla de 2020-12-28 18-01-13](https://user-images.githubusercontent.com/57497888/103249839-bcd3f080-4936-11eb-9d1f-1c0c08f4c9e4.png)

If you can help me how to increase the txpower I would appreciate it

thank you so muchhhhh!! and thank you for maintaining and updating these codes

**Comment by kimocoder** [comment]
`ip link set wlan12345532 down`
`iw dev wlan12345532 set type monitor'
'ip link set wlan12345532 up`
`iw wlan12345532 set txpower fixed 3000`

or instead of iw, with iwconfig;
`iwconfig wlan12345532 txpower 22` eg

**Comment by SmillerMP** [comment]
![Captura de pantalla de 2020-12-28 18-38-58](https://user-images.githubusercontent.com/57497888/103250933-0c68eb00-493c-11eb-861c-43e992f916ca.png)

This comes out, but it's not that important, so thanks
